#!/bin/bash
MAIN="./main.go"
PKG_NAME="rfid-access-control"
BIN_DIR="./bin"

echo 'building.. windows x86'
CGO_ENABLED=0 GOOS=windows GOARCH=386 go build  -o "$BIN_DIR/$PKG_NAME.x86.exe" "$MAIN"

echo 'building.. windows x64'
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o "$BIN_DIR/$PKG_NAME.x64.exe" "$MAIN"


echo 'building.. linux x86'
CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o "$BIN_DIR/$PKG_NAME.x86" "$MAIN"

echo 'building.. linux x64'
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o "$BIN_DIR/$PKG_NAME.x64" "$MAIN"

# for macos
echo 'building.. macos x86'
CGO_ENABLED=0 GOOS=darwin GOARCH=386 go build -o "$BIN_DIR/$PKG_NAME.x86.mac" "$MAIN"
echo 'building.. macos x64'
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o "$BIN_DIR/$PKG_NAME.x64.mac" "$MAIN"
